# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache D:/GitHub/ITC/A_Guide_to_Digital_Design_and_Synthesis/Projects/UART/VivadoProjects/uart/.Xil/Vivado-10968-DESKTOP-FSNETFU/incrSyn
set_param simulator.questaInstallPath C:/questasim64_2021.1/win64
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/GitHub/ogni/projects/vivado/i2c_exam/i2c_exam.cache/wt [current_project]
set_property parent.project_path D:/GitHub/ogni/projects/vivado/i2c_exam/i2c_exam.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-a7-35:part0:1.0 [current_project]
set_property ip_repo_paths d:/GitHub/VivaIP/ip_repo [current_project]
update_ip_catalog
set_property ip_output_repo d:/GitHub/ogni/projects/vivado/i2c_exam/i2c_exam.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/GitHub/ogni/projects/vivado/i2c_exam/i2c_exam.srcs/sources_1/imports/srcs/baud_gen.v
  D:/GitHub/ogni/projects/vivado/i2c_exam/i2c_exam.srcs/sources_1/imports/srcs/fifo.v
  D:/GitHub/ogni/projects/vivado/i2c_exam/i2c_exam.srcs/sources_1/imports/srcs/fifo_ctrl.v
  D:/GitHub/ogni/projects/vivado/i2c_exam/i2c_exam.srcs/sources_1/imports/srcs/reg_file.v
  D:/GitHub/ogni/projects/vivado/i2c_exam/i2c_exam.srcs/sources_1/imports/srcs/uart.v
  D:/GitHub/ogni/projects/vivado/i2c_exam/i2c_exam.srcs/sources_1/imports/srcs/uart_rx.v
  D:/GitHub/ogni/projects/vivado/i2c_exam/i2c_exam.srcs/sources_1/imports/srcs/uart_tx.v
  D:/GitHub/ogni/projects/vivado/i2c_exam/i2c_exam.srcs/sources_1/imports/srcs/uart_top.v
}
read_ip -quiet d:/GitHub/ogni/projects/vivado/i2c_exam/i2c_exam.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/GitHub/ogni/projects/vivado/i2c_exam/i2c_exam.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/ogni/projects/vivado/i2c_exam/i2c_exam.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/ogni/projects/vivado/i2c_exam/i2c_exam.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/GitHub/ogni/projects/vivado/i2c_exam/i2c_exam.srcs/constrs_1/imports/srcs/Arty_Master.xdc
set_property used_in_implementation false [get_files D:/GitHub/ogni/projects/vivado/i2c_exam/i2c_exam.srcs/constrs_1/imports/srcs/Arty_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top uart_top -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef uart_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file uart_top_utilization_synth.rpt -pb uart_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
